# Generated by Django 5.0.3 on 2024-12-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horariomanagerapp', '0002_characteristics'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='fail_regulation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='no_room',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='overcrowded',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='overlap',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='wrong_characteristics',
            field=models.FloatField(default=0),
        ),
    ]
