# Generated by Django 5.0.3 on 2024-12-16 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horariomanagerapp', '0003_schedule_fail_regulation_schedule_no_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='fail_regulation',
            new_name='time_regulation',
        ),
    ]
