# Generated by Django 5.0.3 on 2024-12-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horariomanagerapp', '0004_rename_fail_regulation_schedule_time_regulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='no_room',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='overcrowded',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='overlap',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_regulation',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wrong_characteristics',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
